channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.1.2
- pip:
  - mlflow==2.11.1
  - category-encoders==2.6.3
  - cffi==1.16.0
  - click==8.1.7
  - cloudpickle==2.2.1
  - cupy-cuda12x==12.2.0
  - cvxopt==1.3.2
  - defusedxml==0.7.1
  - distributed==2023.8.1
  - graphviz==0.20.1
  - imbalanced-learn==0.10.1
  - importlib-metadata==7.0.2
  - ipython==7.34.0
  - jinja2==3.1.3
  - lightgbm==4.1.0
  - matplotlib==3.7.1
  - numpy==1.25.2
  - packaging==23.2
  - pandas==1.5.3
  - pathlib==1.0.1
  - pyarrow==14.0.2
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.4
name: mlflow-env
