name: ci_deploiement_API_pythonanywhere_new

# Workflow declenché lors d'un push sur branche main & manuellement sur Github
on:
  push:
    branches:
    - main
  workflow_dispatch:

# 2 jobs dans le workflow : build & deploy
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: create public key
      uses: DamianReeves/write-file-action@master
      with:
        path: ~/.ssh/id_rsa_github.pub
        contents: |
          ${{ secrets.PUBKEY }}
        write-mode: overwrite

    - name: debug
      run: |
        chmod 600 ~/.ssh/id_rsa_github.pub
        echo "Public Key: $(cat ~/.ssh/id_rsa_github.pub)"
        ls ~/.ssh

    - name: Deploy Pythonanywhere
      run: |
        ssh -o StrictHostKeyChecking=no -v ${{ secrets.USERNAME }}@www.eu.pythonanywhere.com ls

    - name: Print debugging information
      run: |
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"
        echo "Contents of Working Directory: $(ls -l)"
  