name: ci_deploiement_API_pythonanywhere

# Workflow declenché lors d'un push sur branche main & manuellement sur Github
on:
  push:
    branches:
    - main
  workflow_dispatch:

# 2 jobs dans le workflow : build & deploy
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Berthe_Pierrick_4_dossier_code_02204

    steps:
    - uses: actions/checkout@v4

    - name: installation_python_version_3.11.5
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'

    - name: creation_virtual_env
      run: |
        python -m venv env
        source env/bin/activate

    - name: installation_requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print debugging information
      run: |
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"
        echo "Contents of Working Directory: $(ls -l)"
        echo "Contents of site-packages: $(ls -l env/lib/python*/site-packages)"

    - name: tests_unitaires_API
      run: |
        python tests_unitaires/test_unitaire_api.py

    - name: save_artifact_for_deploy_job
      uses: actions/upload-artifact@v4
      with:
        name: API_pythonanywhere
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: Berthe_Pierrick_4_dossier_code_02204

    steps:
    - name: download_artifact_for_deploy_job
      uses: actions/download-artifact@v4
      with:
        name: API_pythonanywhere
        path: .

    - name: Re-Deploy Pythonanywhere Django API
      uses: umuttopalak/pythonanywhere-deploy-action@v1.0.0
      with:
        host: 'www.eu.pythonanywhere.com'
        username: ${{ secrets.USERNAME }}
        api_token: ${{ secrets.API_TOKEN }}
        domain_name: ${{ secrets.DOMAIN_NAME }}
        console_id:  ${{ secrets.CONSOLE_ID }}