name: ci_deploiement_API_pythonanywhere_new

# Workflow declenché lors d'un push sur branche main & manuellement sur Github
on:
  push:
    branches:
    - main
  workflow_dispatch:

# 2 jobs dans le workflow : build & deploy
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Create pubkey
      run: |
        echo "${{ secrets.PUBKEY }}" > ~/.ssh/id_pythonanywhere.pub
        chmod 600 ~/.ssh/id_pythonanywhere.pub
        
    - name: Deploy Pythonanywhere
      run: |
        ssh -o StrictHostKeyChecking=no -v ${{ secrets.USERNAME }}@www.eu.pythonanywhere.com ls

    - name: Print debugging information
      run: |
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"
        echo "Contents of Working Directory: $(ls -l)"
  