name: ci_deploiement_API_heroku

# Workflow declenché lors d'un push sur branche main & manuellement sur Github
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:

  # Deploy sur cloud pythonanywhere par ssh
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-pb" #Must be unique in Heroku
          heroku_email: "pierrick.berthe@gmx.fr"



    # steps:
    # - name: testing pythonanywhere server ssh connection
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host : ${{ secrets.HOST_PYTHONANYWHERE }}
    #     username : ${{ secrets.USERNAME }}
    #     key : ${{ secrets.OMG_SECRET }}
    #     port : 22
    #     script : |
    #       pwd
    #       ls
    #       if [ -d "Projet7_OCR_DataScientist" ]; then
    #         cd Projet7_OCR_DataScientist
    #         git pull origin main
    #       else
    #         git clone git@github.com:pierrickBERTHE/Projet7_OCR_DataScientist.git
    #         python -m venv env
    #         source env/bin/activate
    #         python -m pip install --upgrade pip
    #         cd Projet7_OCR_DataScientist
    #         git status
    #         pip install -r requirements.txt
    #       fi
    #       cd Berthe_Pierrick_4_dossier_code_022024
    #       pwd
    #       ls
    #       echo "Contents of site-packages: $(ls -l env/lib/python*/site-packages)"
